-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyWpFdVUptUKJTFm/
Nt/B5FHb2o30JcKv3v8jJ/Yj3jmgCgYIKoZIzj0DAQehRANCAATOXft4FB+ZaMWv
8i8ZylgH8dlN7HxfiuDExZhXwQ3X94ionUsXmeaezx2Bw1LfUhbwuXVVe5ZHV3jr
ZpCwNnMs
-----END PRIVATE KEY-----