# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  private_lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_content: ENV.fetch("ASC_PRIVATE_KEY"),
      is_key_content_base64: true,
      in_house: false
    )
  end

  desc "Install existing App Store signing assets on a CI runner"
  lane :prepare_ci_signing do
    keychain_name = "bodybuddies-ci"
    keychain_password = ENV.fetch("CI_KEYCHAIN_PASSWORD", "temporary-ci-keychain")

    delete_keychain(name: keychain_name) if File.exist?(
      File.expand_path("~/Library/Keychains/#{keychain_name}-db")
    )
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
    match(
      type: "appstore",
      readonly: true,
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      git_url: ENV.fetch(
        "MATCH_GIT_URL",
        "https://github.com/TeamBocean/bodybuddiesapp.git"
      ),
      git_basic_authorization: ENV.fetch("MATCH_GIT_BASIC_AUTHORIZATION"),
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
  end

  desc "Upload an already-built IPA to TestFlight"
  lane :upload_ipa do |options|
    ipa_path = options[:ipa_path]
    UI.user_error!("Pass ipa_path:/absolute/path/to/app.ipa") if ipa_path.to_s.empty?
    UI.user_error!("IPA not found at #{ipa_path}") unless File.exist?(ipa_path)

    upload_to_testflight(
      api_key: load_asc_api_key,
      ipa: ipa_path,
      skip_waiting_for_build_processing: true
    )
  end
end
