# Automatically update fastlane
default_platform(:ios)


TEMP_KEYCHAIN_NAME = "Runner"
TEMP_KEYCHAIN_PASSWORD = "appname"

# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Create the temporary keychain with name and password
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: true,
    timeout: 0
  )
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end


platform :ios do

  desc "Generate prod iOS app"
  lane :build_prod do
    create_unlock_keychain
    generate_signed_prod
    delete_temp_keychain(TEMP_KEYCHAIN_NAME)
  end

  desc "Build & sign production"
  lane :generate_signed_prod do
    disable_signing
    # (optional, you must specify the path to your main Xcode project if it is not in the project root directory))
    # match appstore
   match_profile
   match_profile_share_extension(
    target:'prod'
    )
    # sh "bash ./flutter_build.sh --clean"
    build_ios_app(
      scheme: "Runner",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
           "com.bodybuddies.bodybuddiesapp" => "match AppStore com.bodybuddies.bodybuddiesapp",
        }
      }
      output_name: "Recspot",
    )
  end

  desc "Generate staging iOS app"
  lane :build_staging do
    create_unlock_keychain
    generate_signed_staging
    delete_temp_keychain(TEMP_KEYCHAIN_NAME)
  end

  desc "Build & sign Staging"
  lane :generate_signed_staging do
    disable_signing
    # (optional, you must specify the path to your main Xcode project if it is not in the project root directory))
    # match appstore
    match_profile
    match_profile_share_extension(
        target:"stage"
    )
    # sh "bash ./flutter_build.sh --clean"
    build_ios_app(
      scheme: "staging",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
           "com.bodybuddies.bodybuddiesapp" => "match AppStore com.bodybuddies.bodybuddiesapp",
        }
      }
      output_name: "RecspotStaging",
    )
  end

  desc "Generate dev iOS app"
  lane :build_dev do
    create_unlock_keychain
    generate_signed_dev
    delete_temp_keychain(TEMP_KEYCHAIN_NAME)
  end

  desc "Build & sign dev"
  lane :generate_signed_dev do
    disable_signing
    # (optional, you must specify the path to your main Xcode project if it is not in the project root directory))
    # match appstore
    match_profile
    match_profile_share_extension(
    target:"test"
    )
    # sh "bash ./flutter_build.sh --clean"

    build_ios_app(
      scheme: "Runner",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
           "com.bodybuddies.bodybuddiesapp" => "match AppStore com.bodybuddies.bodybuddiesapp",
        }
      }
      output_name: "RecspotDev",
    )
  end


  desc "Upload Production iOS app to AppStoreConnect"
  lane :deploy_prod do |options|
    create_unlock_keychain
    increment_build_number(
    build_number: (options[:resetBuild] ? 1 : latest_testflight_build_number + 1),
    xcodeproj: "./Runner.xcodeproj")
    increment_version_number(
      version_number: "1.1.1",      # specify specific version number (optional, omitting it increments patch version number)
      xcodeproj: "./Runner.xcodeproj"  # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
    )
    generate_signed_prod
    pilot(
        skip_submission: false,
        skip_waiting_for_build_processing: true,
        ipa: "./Recspot.ipa"
    )
    delete_temp_keychain(TEMP_KEYCHAIN_NAME)
  end
  
  desc "Upload Staging app to AppStoreConnect"
  lane :deploy_staging do 
    create_unlock_keychain
    increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "./Runner.xcodeproj")
    generate_signed_staging
    pilot(
        skip_submission: false,
        skip_waiting_for_build_processing: true,
        ipa: "./RecspotStaging.ipa"
    )
    delete_temp_keychain(TEMP_KEYCHAIN_NAME)
  end

  desc "Upload Dev iOS app to AppStoreConnect"
  lane :deploy_dev do
    create_unlock_keychain
    increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "./Runner.xcodeproj")
    increment_version_number(
      version_number: "3.0.0",      # specify specific version number (optional, omitting it increments patch version number)
      xcodeproj: "./Runner.xcodeproj"  # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
    )
    generate_signed_dev
    pilot(
        skip_submission: false,
        skip_waiting_for_build_processing: true,
        ipa: "./RecspotDev.ipa"
    )
    delete_temp_keychain(TEMP_KEYCHAIN_NAME)
  end

  # desc "Upload iOS app to AppStore"
  # lane :deploy_prod do
  #   deliver(
  #     skip_metadata: true,
  #     skip_screenshots: true,
  #     submit_for_review: true,
  #     force: true,
  #     ipa: "./Runner.ipa",
  #   )
  # end

  desc "Disable Automatic signing"
  lane :disable_signing do |options|

    profile_names =  "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}"

  puts profile_names
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution",
    )
  profile_names_share =  "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}.Share-Extension"
  puts profile_names_share
        disable_automatic_code_signing(
          path: "./Runner.xcodeproj",
          team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
          profile_name: "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}.Share-Extension",
          code_sign_identity: "iPhone Distribution",
          targets: ["Share Extension"]
        )
  end

  desc "Keychain creation and unlocking."
  lane :create_unlock_keychain do
    keychain_name = TEMP_KEYCHAIN_NAME
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
    unlock_keychain( # By default the keychain is added to the existing. To replace them with the selected keychain you may use `:replace`
      path: "~/Library/Keychains/#{keychain_name}-db",
      password: keychain_password,
      add_to_search_list: :add # To only add a keychain use `true` or `:add`.
    )
  end
  desc "Match provisioning profile"
  lane :match_profile do
    match(
      readonly: true,
      keychain_name: TEMP_KEYCHAIN_NAME,
      keychain_password: TEMP_KEYCHAIN_PASSWORD,
    )
  end

  lane :match_profile_share_extension do |options|
  target = options[:target]
  identifier = target == 'prod'?  'com.bodybuddies.bodybuddiesapp' :  "com.bodybuddies.bodybuddiesapp"
    match(
    type: 'appstore',
    app_identifier:identifier,
    keychain_name: TEMP_KEYCHAIN_NAME,
    keychain_password: TEMP_KEYCHAIN_PASSWORD,
    )
  end
end
