fastlane_version '2.157'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :beta do
      build_app(
        scheme: "MyApp",
        workspace: "Runner.xcworkspace",
        export_method: "app-store"
      )
    end
end
